"""Markdown report formatter."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from graphsast.analysis.models import Finding

_SEV_ICON = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🔵"}
_VERDICT_ICON = {"CONFIRMED": "✅", "FALSE_POSITIVE": "❌", "NEEDS_REVIEW": "❓"}


def to_markdown(findings: list[Finding], target: Path, elapsed: float = 0.0) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    active     = [f for f in findings if not f.is_false_positive]
    false_pos  = [f for f in findings if f.is_false_positive]

    lines: list[str] = [
        "# GraphSAST Security Report",
        "",
        f"**Target:** `{target}`  ",
        f"**Scanned:** {ts}  ",
        f"**Elapsed:** {elapsed:.1f}s  ",
        "",
        "## Summary",
        "",
        "| Severity | Count |",
        "|---|---|",
    ]

    counts: dict[str, int] = {}
    for f in active:
        sev = f.effective_severity
        counts[sev] = counts.get(sev, 0) + 1

    for sev in ("CRITICAL", "HIGH", "MEDIUM", "LOW"):
        icon = _SEV_ICON.get(sev, "")
        lines.append(f"| {icon} {sev} | {counts.get(sev, 0)} |")
    lines.append(f"| **Active total** | **{len(active)}** |")
    if false_pos:
        lines.append(f"| ~~False positives~~ | {len(false_pos)} |")
    lines.append("")

    if not active:
        lines.append("> No active findings.")
    else:
        for sev in ("CRITICAL", "HIGH", "MEDIUM", "LOW"):
            bucket = [f for f in active if f.effective_severity == sev]
            if not bucket:
                continue
            icon = _SEV_ICON.get(sev, "")
            lines.append(f"## {icon} {sev} ({len(bucket)})")
            lines.append("")
            for i, f in enumerate(bucket, 1):
                lines.extend(_render(f, i, target))

    if false_pos:
        lines += [
            "---",
            "## False positives (LLM ruled out)",
            "",
            "<details><summary>Show</summary>",
            "",
        ]
        for i, f in enumerate(false_pos, 1):
            lines.extend(_render(f, i, target))
        lines.append("</details>")

    lines += ["", "---", "*Generated by GraphSAST*"]
    return "\n".join(lines)


def _render(f: Finding, idx: int, target: Path) -> list[str]:
    try:
        rel = Path(f.file_path).relative_to(target).as_posix()
    except ValueError:
        rel = f.file_path or "unknown"

    loc = f"`{rel}` line {f.line_start}" if f.line_start else f"`{rel}`"

    # CVSS badge
    cvss_cell = "—"
    if f.llm_cvss_score is not None:
        score = f.llm_cvss_score
        rating = (
            "Critical" if score >= 9.0 else
            "High"     if score >= 7.0 else
            "Medium"   if score >= 4.0 else
            "Low"
        )
        cvss_cell = f"**{score:.1f}** ({rating})"
        if f.llm_cvss_vector:
            cvss_cell += f"<br>`{f.llm_cvss_vector}`"

    lines = [
        f"### {idx}. {f.title}",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| **Rule** | `{f.rule_id}` |",
        f"| **Severity** | {f.effective_severity} |",
        f"| **CVSS** | {cvss_cell} |",
        f"| **CWE** | {f.cwe_id or '—'} |",
        f"| **Location** | {loc} |",
    ]

    if f.llm_verdict:
        icon = _VERDICT_ICON.get(f.llm_verdict, "")
        lines.append(f"| **LLM verdict** | {icon} {f.llm_verdict} |")

    lines.append("")

    # Description (LLM) — more detailed than the Semgrep message
    if f.llm_description:
        lines += [f.llm_description, ""]
    else:
        lines += [f"> {f.message}", ""]

    # Code snippet
    if f.snippet:
        lines += [
            "**Vulnerable code:**",
            "",
            f"```\n{f.snippet}\n```",
            "",
        ]

    # PoC
    if f.llm_poc:
        lines += [
            "<details><summary>PoC / Exploit scenario</summary>",
            "",
            f.llm_poc,
            "",
            "</details>",
            "",
        ]

    # Reasoning (collapsed)
    if f.llm_reasoning:
        lines += [
            "<details><summary>LLM reasoning</summary>",
            "",
            f.llm_reasoning,
            "",
            "</details>",
            "",
        ]

    return lines
